server:
    port : 8082
profile:
    desc : This property file is specific to PRODUCTION environment
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/USER_DB_PROD
    username: root
    password: root
